# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PySM_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PySm_MainWindow(object):
    def setupUi(self, PySm_MainWindow):
        PySm_MainWindow.setObjectName("PySm_MainWindow")
        PySm_MainWindow.resize(810, 640)
        PySm_MainWindow.setMinimumSize(QtCore.QSize(810, 640))
        PySm_MainWindow.setMaximumSize(QtCore.QSize(810, 640))
        self.centralwidget = QtWidgets.QWidget(PySm_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.grpyEDInputFile = QtWidgets.QGroupBox(self.centralwidget)
        self.grpyEDInputFile.setObjectName("grpyEDInputFile")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.grpyEDInputFile)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(62, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.btnSelectyEDInputFile = QtWidgets.QPushButton(self.grpyEDInputFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectyEDInputFile.sizePolicy().hasHeightForWidth())
        self.btnSelectyEDInputFile.setSizePolicy(sizePolicy)
        self.btnSelectyEDInputFile.setObjectName("btnSelectyEDInputFile")
        self.gridLayout.addWidget(self.btnSelectyEDInputFile, 0, 3, 1, 1)
        self.txtPathToyEDInputFile = QtWidgets.QLineEdit(self.grpyEDInputFile)
        self.txtPathToyEDInputFile.setMinimumSize(QtCore.QSize(500, 0))
        self.txtPathToyEDInputFile.setText("")
        self.txtPathToyEDInputFile.setClearButtonEnabled(True)
        self.txtPathToyEDInputFile.setObjectName("txtPathToyEDInputFile")
        self.gridLayout.addWidget(self.txtPathToyEDInputFile, 0, 2, 1, 1)
        self.lblyEDInputFile = QtWidgets.QLabel(self.grpyEDInputFile)
        self.lblyEDInputFile.setObjectName("lblyEDInputFile")
        self.gridLayout.addWidget(self.lblyEDInputFile, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_7.addWidget(self.grpyEDInputFile, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(287, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 3, 0, 1, 1)
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        self.btnGenerate.setFont(font)
        self.btnGenerate.setObjectName("btnGenerate")
        self.gridLayout_7.addWidget(self.btnGenerate, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(287, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 5, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 6, 1, 1, 1)
        self.txtGenerationOutput = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtGenerationOutput.setObjectName("txtGenerationOutput")
        self.gridLayout_7.addWidget(self.txtGenerationOutput, 7, 0, 1, 3)
        self.grpConfiguration = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpConfiguration.sizePolicy().hasHeightForWidth())
        self.grpConfiguration.setSizePolicy(sizePolicy)
        self.grpConfiguration.setObjectName("grpConfiguration")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.grpConfiguration)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txtGenOutputPath = QtWidgets.QLineEdit(self.grpConfiguration)
        self.txtGenOutputPath.setText("")
        self.txtGenOutputPath.setClearButtonEnabled(True)
        self.txtGenOutputPath.setObjectName("txtGenOutputPath")
        self.gridLayout_5.addWidget(self.txtGenOutputPath, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 1, 1, 1)
        self.lblGenOutputPath = QtWidgets.QLabel(self.grpConfiguration)
        self.lblGenOutputPath.setObjectName("lblGenOutputPath")
        self.gridLayout_5.addWidget(self.lblGenOutputPath, 0, 0, 1, 1)
        self.btnSelectOutputPath = QtWidgets.QPushButton(self.grpConfiguration)
        self.btnSelectOutputPath.setObjectName("btnSelectOutputPath")
        self.gridLayout_5.addWidget(self.btnSelectOutputPath, 0, 4, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblHeaderTemplate = QtWidgets.QLabel(self.grpConfiguration)
        self.lblHeaderTemplate.setObjectName("lblHeaderTemplate")
        self.gridLayout_2.addWidget(self.lblHeaderTemplate, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 1, 1, 1)
        self.txtPathToHeaderTemplate = QtWidgets.QLineEdit(self.grpConfiguration)
        self.txtPathToHeaderTemplate.setText("")
        self.txtPathToHeaderTemplate.setClearButtonEnabled(True)
        self.txtPathToHeaderTemplate.setObjectName("txtPathToHeaderTemplate")
        self.gridLayout_2.addWidget(self.txtPathToHeaderTemplate, 0, 2, 1, 1)
        self.btnSelectHeaderFile = QtWidgets.QPushButton(self.grpConfiguration)
        self.btnSelectHeaderFile.setObjectName("btnSelectHeaderFile")
        self.gridLayout_2.addWidget(self.btnSelectHeaderFile, 0, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblAuthorName = QtWidgets.QLabel(self.grpConfiguration)
        self.lblAuthorName.setObjectName("lblAuthorName")
        self.gridLayout_3.addWidget(self.lblAuthorName, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 1, 1, 1)
        self.txtAuthorName = QtWidgets.QLineEdit(self.grpConfiguration)
        self.txtAuthorName.setText("")
        self.txtAuthorName.setClearButtonEnabled(True)
        self.txtAuthorName.setObjectName("txtAuthorName")
        self.gridLayout_3.addWidget(self.txtAuthorName, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblStateMachineName = QtWidgets.QLabel(self.grpConfiguration)
        self.lblStateMachineName.setObjectName("lblStateMachineName")
        self.gridLayout_4.addWidget(self.lblStateMachineName, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 1, 1, 1)
        self.txtStateMachineName = QtWidgets.QLineEdit(self.grpConfiguration)
        self.txtStateMachineName.setText("")
        self.txtStateMachineName.setClearButtonEnabled(True)
        self.txtStateMachineName.setObjectName("txtStateMachineName")
        self.gridLayout_4.addWidget(self.txtStateMachineName, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.grpConfiguration, 1, 0, 1, 3)
        PySm_MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PySm_MainWindow)
        self.statusbar.setObjectName("statusbar")
        PySm_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PySm_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(PySm_MainWindow)
        PySm_MainWindow.setTabOrder(self.txtPathToyEDInputFile, self.btnSelectyEDInputFile)
        PySm_MainWindow.setTabOrder(self.btnSelectyEDInputFile, self.txtGenOutputPath)
        PySm_MainWindow.setTabOrder(self.txtGenOutputPath, self.btnSelectOutputPath)
        PySm_MainWindow.setTabOrder(self.btnSelectOutputPath, self.txtPathToHeaderTemplate)
        PySm_MainWindow.setTabOrder(self.txtPathToHeaderTemplate, self.btnSelectHeaderFile)
        PySm_MainWindow.setTabOrder(self.btnSelectHeaderFile, self.txtAuthorName)
        PySm_MainWindow.setTabOrder(self.txtAuthorName, self.txtStateMachineName)
        PySm_MainWindow.setTabOrder(self.txtStateMachineName, self.btnGenerate)
        PySm_MainWindow.setTabOrder(self.btnGenerate, self.txtGenerationOutput)

    def retranslateUi(self, PySm_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        PySm_MainWindow.setWindowTitle(_translate("PySm_MainWindow", "PySM - The python state machine generator"))
        self.grpyEDInputFile.setTitle(_translate("PySm_MainWindow", "yED Input File (*.graphml)"))
        self.btnSelectyEDInputFile.setText(_translate("PySm_MainWindow", "Browse"))
        self.txtPathToyEDInputFile.setPlaceholderText(_translate("PySm_MainWindow", "path/to/yED_Input_File.graphml"))
        self.lblyEDInputFile.setText(_translate("PySm_MainWindow", "yED Input File:"))
        self.btnGenerate.setText(_translate("PySm_MainWindow", "Generate!"))
        self.grpConfiguration.setTitle(_translate("PySm_MainWindow", "Configuration"))
        self.txtGenOutputPath.setPlaceholderText(_translate("PySm_MainWindow", "OUT"))
        self.lblGenOutputPath.setText(_translate("PySm_MainWindow", "Generation output path"))
        self.btnSelectOutputPath.setText(_translate("PySm_MainWindow", "Browse"))
        self.lblHeaderTemplate.setText(_translate("PySm_MainWindow", "Header Comment File"))
        self.txtPathToHeaderTemplate.setPlaceholderText(_translate("PySm_MainWindow", "defaultCodeHeader.txt"))
        self.btnSelectHeaderFile.setText(_translate("PySm_MainWindow", "Browse"))
        self.lblAuthorName.setText(_translate("PySm_MainWindow", "Author name"))
        self.txtAuthorName.setPlaceholderText(_translate("PySm_MainWindow", "AuthorName"))
        self.lblStateMachineName.setText(_translate("PySm_MainWindow", "State machine name"))
        self.txtStateMachineName.setPlaceholderText(_translate("PySm_MainWindow", "stateMachineName (e.g. mvcSm1)"))

