/******************************************************************************
 *                                                                            *
 * Generated by pySM - The python state machine code generator                *
 *                                                                            *
 *****************************************************************************/

/**
 * @file NestedStates.h
 * @author Markus Burger
 * @date 2017-12-24
 * @brief Header for generated state machine nestedStates
 * Hand-written test file
 */
 
#ifndef NESTEDSTATES_H_
#define NESTEDSTATES_H_

/* ========================================================================= */
/* INCLUDES                                                                  */
/* ========================================================================= */
#include "PySm_types.h"
#include "PySm.h"


/* ========================================================================= */
/* USER PREPROCESSOR DIRECTIVES                                              */
/* ========================================================================= */


/* ========================================================================= */
/* TYPEDEFS                                                                  */
/* ========================================================================= */
/**
 * @brief Structure defining input signals for state machine
 * nestedStates
*/
typedef struct
{
	pySm_bool trigger_a;
	pySm_bool trigger_b;
	pySm_bool trigger_c;
	pySm_bool trigger_d;
	pySm_bool trigger_e;
	pySm_bool trigger_f;
	pySm_bool trigger_g;
	pySm_bool trigger_h;
	pySm_bool trigger_i;
} nestedStates_inputSignalsType;


/**
 * @brief Structure defining output signals for state machine
 * nestedStates
*/
typedef struct
{
	pySm_bool testOutput;
} nestedStates_outputSignalsType;


/**
 * @brief Enum for exporting current active state of state machine
 * simpleEx
*/
typedef enum
{
	NESTEDSTATES_RESERVED_INVALID_STATE = -2,
	NESTEDSTATES_RESERVED_STATE_HAS_NO_SUPERSTATE,
	NESTEDSTATES_SUP_A,
	NESTEDSTATES_SUP_B,
	NESTEDSTATES_SUP_C,
	NESTEDSTATES_SUP_D,
	NESTEDSTATES_SUB_A,
	NESTEDSTATES_SUB_B,
	NESTEDSTATES_SUB_C,
	NESTEDSTATES_SUB_D,
	NESTEDSTATES_SUB_E,
	NESTEDSTATES_SUB_F
} nestedStates_activeStateType;


/* ========================================================================= */
/* API DECLARATION                                                           */
/* ========================================================================= */
/**
 * @brief Main function of the state machine
 * simpleEx
*/
pySm_returnType NestedStates_mainFunction(nestedStates_inputSignalsType*, nestedStates_outputSignalsType*);


/**
 * @brief Main function of the state machine
 * simpleEx
*/
void NestedStates_getActiveState(nestedStates_activeStateType*);


#endif /* SIMPLEEX_H_ */
