/******************************************************************************
 *                                                                            *
 * Generated by pySM - The python state machine code generator                *
 *                                                                            *
 *****************************************************************************/

/**
 * @file DevCoffee.h
 * @author Markus Burger
 * @date 2017-10-01
 * @brief Header for generated state machine devCoffee
 * Generated 2017-10-01 17:02:39 by PySM - The python state machine generator.
 */
 
#ifndef DEVCOFFEE_H_
#define DEVCOFFEE_H_

/* ========================================================================= */
/* INCLUDES                                                                  */
/* ========================================================================= */
#include "PySm_types.h"
#include "PySm.h"


/* ========================================================================= */
/* USER PREPROCESSOR DIRECTIVES                                              */
/* ========================================================================= */
#define WORKTIME_PER_DAY_H 8
#define WAKE_UP_TIME_H 6 /* stand up at 6 o'clock */
#define GO_HOME_TIME (WORKTIME_PER_DAY_H+WAKE_UP_TIME_H)


/* ========================================================================= */
/* TYPEDEFS                                                                  */
/* ========================================================================= */
/**
 * @brief Structure defining input signals for state machine
 * devCoffee
*/
typedef struct
{
	pySm_bool developer_is_ill_HA_b;
	pySm_uint8 another_input_ui8;
} devCoffee_inputSignalsType;


/**
 * @brief Structure defining output signals for state machine
 * devCoffee
*/
typedef struct
{
	pySm_bool developer_is_productive_HA_b;
	pySm_uint16 and_another_output_ui16;
} devCoffee_outputSignalsType;


/**
 * @brief Enum for exporting current active state of state machine
 * devCoffee
*/
typedef enum
{
	devCoffee_UNINITALIZED_STATE_MACHINE,
	DEVCOFFEE_BREAKFAST,
	DEVCOFFEE_IN_OFFICE,
	DEVCOFFEE_GET_COFFEE,
	DEVCOFFEE_RELAX_AND_SLEEP,
	DEVCOFFEE_DEVELOPER_IS_ILL,
} devCoffee_activeStateType;


/* ========================================================================= */
/* API DECLARATION                                                           */
/* ========================================================================= */
/**
 * @brief Main function of the state machine
 * devCoffee
*/
pySm_returnType DevCoffee_mainFunction(devCoffee_inputSignalsType*, devCoffee_outputSignalsType*);


/**
 * @brief Main function of the state machine
 * devCoffee
*/
void DevCoffee_getActiveState(devCoffee_activeStateType*);


#endif /* DEVCOFFEE_H_ */
